config/routes.rb
Micropost::Application.routes.draw do
  scope '(:locale)' do
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :sessions,   only: [:new, :create, :destroy]

    resources :searchs,    only: [:showResult]
    
    resources :microblogs, only: [:create, :destroy] do
      member do
        get :expand, :view_conversation
      end
    end
    resources :relationships, only: [:create, :destroy]
    
    root to: 'static_pages#home'

    match '/search',  to: 'searchs#showResult'
    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    match '/help',    to: 'static_pages#help'
    match '/about',   to: 'static_pages#about'
    match '/contact', to: 'static_pages#contact'
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microblogs">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>

	<% if feed_item.replying? %>
		<span class="view">
      <%= link_to t('.view_conversation'), 
      	  view_conversation_microblog_path(feed_item.id), remote: true %>
    </span>
  <% else %>  
    <span class=" expand">
      <%= link_to t('.exapnd'), expand_microblog_path(feed_item.id), 
      remote: true %>
    </span>
	<% end %>

	<span class="reply">
		<%= link_to t('.reply'), '#' %>
	</span>

	<span class="retweet">
		<%= link_to "retweet", '#' %>
	</span>

	<span class="timestamp">
		<%= t('.posted') %> <%= time_ago_in_words(feed_item.created_at) %> <%= t('.ago') %>.
	</span>

	<% if current_user?(feed_item.user) %>
		<%= link_to t('.delete'), feed_item, method: :delete,
		                                 data: { confirm: "You sure?" },
		                                 title: feed_item.content %>
	<% end %>


	<div class="reply_form">
		<%= form_for @microblog, :html => { :id => '', :class => 'reply_micropost' } do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class="field">
				<%= f.text_area :content,  :id => "reply_form_#{feed_item.id}",
				    placeholder: "Reply..." %>
			</div>
			<div><%= f.hidden_field :in_reply_to, :value => feed_item.id %></div>
			<%= f.submit t('.reply_button'), class: "btn btn-small btn-primary" %>
	  <% end %>
  </div>

  <div class="retweet_form">
  	<%= form_for(@microblog) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content %>
	</div>
	<%= f.submit "retweet", class: "btn btn-small btn-primary" %>
<% end %>
  </div>
</li>

app/views/shared/_microblog_form.html.erb
<%= form_for(@microblog) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new microblog..." %>
	</div>
	<%= f.submit t('.post'), class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_replied.html.erb
  <% if !@replied.empty? %>
	  <ul class="replied_microblogs">
			<% @replied.each do |msg| %>
				<li>
					<%= link_to gravatar_for(msg.user), msg.user %>
					<span class="user">
						<%= link_to msg.user.name, msg.user %>
					</span>
					<span class="content"><%= msg.content %></span>
				</li>
			<% end %>
		</ul>
	<% end %>

app/views/shared/_replying.html.erb
<% if !@reply_microblog.empty? %>
		<ul class="replying_microblogs">
			<% @reply_microblog.each do |msg| %>
				<li>
					<%= link_to gravatar_for(msg.user), msg.user %>
					<span class="user">
						<%= link_to msg.user.name, msg.user %>
					</span>
					<span class="content"><%= msg.content %></span>
				</li>
			<% end %>
		</ul>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="folllowing" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a> 
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to t('.view_my_profile'), current_user %>
</span>
<span>
	<%= pluralize(current_user.microblogs.count, "microblog") %>
</span>