config/routes.rb
Micropost::Application.routes.draw do
  scope '(:locale)' do
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :sessions,   only: [:new, :create, :destroy]

    resources :searchs,    only: [:showResult]
    
    resources :microblogs, only: [:create, :destroy] do
      member do
        get :expand, :view_conversation
      end
    end
    resources :relationships, only: [:create, :destroy]
    
    root to: 'static_pages#home'

    match '/search',  to: 'searchs#showResult'
    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

    match '/help',    to: 'static_pages#help'
    match '/about',   to: 'static_pages#about'
    match '/contact', to: 'static_pages#contact'
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Microblog
		by 夏慎川
	</small>
	<nav>
		<ul>
			<li><%= link_to t('.about'),   about_path %></li>
			<li><%= link_to t('.contact'), contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
  		<div class="container">
  			<%= link_to "microblog", root_path, id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <% if signed_in? %>
              <li id="search">
                <%= form_for(:searchs, url: search_path,html: { method: :get })  do |f| %>
                  <%= f.text_field :name ,class: 'search-query',placeholder: 'Search'%>
                  <%= f.submit t('.search'), class: "btn btn-small" %>
                <% end %>
              </li>
            <% end %>
            <li><%= link_to t('.home'),     root_path %></li>
            <li><%= link_to t('.help'),     help_path %></li>
            <% if signed_in? %>
              <li><%= link_to t('.users'), users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t('.accout') %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('.profile'), current_user %></li>
                  <li><%= link_to t('.settings'), edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t('.sign_out'), signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to t('.sign_in'), signin_path %></li>
            <% end %>
            <li id="banner">
              <%= form_tag root_path, class: 'locale' do %>
                <%= select_tag 'set_locale',
                  options_for_select(LANGUAGES, I18n.locale.to_s),
                  onchange: 'this.form.submit()' %>
                <%= submit_tag 'submit' %>
                <%= javascript_tag "$('.locale input').hide()" %>
              <% end %>
            </li>
          </ul>
        </nav>
  		</div>
    </div>
	</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>